In [ ]:
import numpy as np

Understanding Data Types in Python

In [ ]:
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}

In [ ]:
# Python code
result = 0
for i in range(100):
    result += i

In [1]:
L = list(range(10))
L
type(L[0])

int

 a list of strings:

In [2]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

heterogenous list

In [ ]:
L3 = [True, "2", 3.0, 4]

In [24]:
from random import randint,randrange

In [ ]:
import numpy as np
# integer array:
np.array([1, 4, 2, 5, 3])

arrays

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

In [ ]:
a=[23,45,67]
len(a)
np.std(a)
np.var(a)

In [22]:
for x in range(10,20):
    print(x)

10
11
12
13
14
15
16
17
18
19


In [25]:
for x in range(10,50):
    print(randrange(15))

11
7
14
11
2
12
1
0
7
7
8
0
14
14
12
11
7
12
4
9
11
4
1
2
12
5
0
4
1
13
9
5
5
11
9
10
7
3
14
4


In [ ]:
def mynewfunction(x,y):
    z=x**2+3*x**2*y+20*y**2
    print(z)

In [ ]:
mynewfunction(1,3)

190


In [ ]:
mynewfunction(10,30)

27100


In [ ]:
def mybadfunction(x,y):
    z=x**2+3*x**2*y+20*y**2
    return(z)


In [ ]:
mybadfunction(1,1)

24

In [ ]:
scores=(23,46,69,7,5)

In [ ]:
type(scores)

tuple

In [ ]:
sc=(46,45)

In [ ]:
type(sc)

tuple

In [ ]:
scores+sc

(23, 46, 69, 7, 5, 46, 45)

In [ ]:
import pandas as pd

In [ ]:
adult=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")

In [ ]:
#pd.read_csv?
'''this is 
a multiple
line comment
'''

'this is \na multiple\nline comment\n'

In [ ]:
adult.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [ ]:
adult.columns

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [ ]:
adult.columns=["age ",
"workclass ",
"fnlwgt",
"education ",
"education-num",
"marital-status",
"occupation",
"relationship",
"race",
"sex",
"capital-gain",
"capital-loss",
"hours-per-week",
"native-country",
"income",
]

In [ ]:
wb=pd.read_json("C:\\Users\\KOGENTIX\\Desktop\\training\\world_bank.json",lines=True)

In [ ]:
wb.head()

_id  approvalfy board_approval_month  \
0  {'$oid': '52b213b38594d8a2be17c780'}        1999             November   
1  {'$oid': '52b213b38594d8a2be17c781'}        2015             November   
2  {'$oid': '52b213b38594d8a2be17c782'}        2014             November   
3  {'$oid': '52b213b38594d8a2be17c783'}        2014              October   
4  {'$oid': '52b213b38594d8a2be17c784'}        2014              October   

      boardapprovaldate                                 borrower  \
0  2013-11-12T00:00:00Z  FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA   
1  2013-11-04T00:00:00Z                    GOVERNMENT OF TUNISIA   
2  2013-11-01T00:00:00Z   MINISTRY OF FINANCE AND ECONOMIC DEVEL   
3  2013-10-31T00:00:00Z   MIN. OF PLANNING AND INT'L COOPERATION   
4  2013-10-31T00:00:00Z                      MINISTRY OF FINANCE   

            closingdate                              country_namecode  \
0  2018-07-07T00:00:00Z  Federal Democratic Republic of Ethiopia!$!ET   
1                   NaN                      Republic of Tunisia!$!TN   
2                   NaN                                   Tuvalu!$!TV   
3                   NaN                        Republic of Yemen!$!RY   
4  2019-04-30T00:00:00Z                       Kingdom of Lesotho!$!LS   

  countrycode                              countryname    countryshortname  \
0          ET  Federal Democratic Republic of Ethiopia            Ethiopia   
1          TN                      Republic of Tunisia             Tunisia   
2          TV                                   Tuvalu              Tuvalu   
3          RY                        Republic of Yemen  Yemen, Republic of   
4          LS                       Kingdom of Lesotho             Lesotho   

                         ...                           sectorcode source  \
0                        ...                          ET,BS,ES,EP   IBRD   
1                        ...                                BZ,BS   IBRD   
2                        ...                                   TI   IBRD   
3                        ...                                   JB   IBRD   
4                        ...                             FH,YW,YZ   IBRD   

   status  supplementprojectflg  \
0  Active                     N   
1  Active                     N   
2  Active                     Y   
3  Active                     N   
4  Active                     N   

                                              theme1  \
0      {'Name': 'Education for all', 'Percent': 100}   
1  {'Name': 'Other economic management', 'Percent...   
2    {'Name': 'Regional integration', 'Percent': 46}   
3  {'Name': 'Participation and civic engagement',...   
4  {'Name': 'Export development and competitivene...   

                                      theme_namecode    themecode   totalamt  \
0      [{'name': 'Education for all', 'code': '65'}]           65  130000000   
1  [{'name': 'Other economic management', 'code':...        54,24          0   
2  [{'name': 'Regional integration', 'code': '47'...  52,81,25,47    6060000   
3  [{'name': 'Participation and civic engagement'...        59,57          0   
4  [{'name': 'Export development and competitiven...        41,45   13100000   

  totalcommamt                                                url  
0    130000000  http://www.worldbank.org/projects/P129828/ethi...  
1      4700000  http://www.worldbank.org/projects/P144674?lang=en  
2      6060000  http://www.worldbank.org/projects/P145310?lang=en  
3      1500000  http://www.worldbank.org/projects/P144665?lang=en  
4     13100000  http://www.worldbank.org/projects/P144933/seco...  

[5 rows x 50 columns]

In [ ]:
type(adult)

pandas.core.frame.DataFrame

In [ ]:
adult.values

array([[50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [ ]:
b=adult.values

In [ ]:
type(b)

numpy.ndarray

In [ ]:
len(b)

32560

In [ ]:
np.arange(len(b))

array([    0,     1,     2, ..., 32557, 32558, 32559])

In [ ]:
c=["age ",
"workclass ",
"fnlwgt",
"education ",
"education-num",
"marital-status",
"occupation",
"relationship",
"race",
"sex",
"capital-gain",
"capital-loss",
"hours-per-week",
"native-country",
"income",
]

In [ ]:
b

array([[50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [ ]:
d=np.arange(len(b))

In [ ]:
d

array([    0,     1,     2, ..., 32557, 32558, 32559])